import assert from 'node:assert/strict';
import { PulseXClient, PulseXError } from '../sdk/javascript/index.mjs';

const calls=[];
const fakeFetch=async (url,opts={})=>{
  calls.push({url,opts});
  if(url.endsWith('/api/auth/login')) return {ok:true,status:200,json:async()=>({user:{id:'u1'},csrf:'csrf-js'})};
  if(url.endsWith('/api/admin/sites')) return {ok:true,status:200,json:async()=>({sites:[]})};
  if(url.endsWith('/api/admin/sites/agency-01/devices') && opts.method==='GET') return {ok:true,status:200,json:async()=>({devices:[]})};
  if(url.endsWith('/api/public/events/demo/guests/register')) return {ok:true,status:200,json:async()=>({guest_number:'G-1111-2222-3333-4444',created:true})};
  if(url.endsWith('/api/public/events/demo/guests/G-1111-2222-3333-4444')) return {ok:true,status:200,json:async()=>({guest_number:'G-1111-2222-3333-4444',status:'registered'})};
  if(url.endsWith('/api/device/events/event-demo/guest-manifest')) return {ok:true,status:200,json:async()=>({guests:[{guest_number:'G-1111-2222-3333-4444'}]})};
  if(url.endsWith('/api/device/events/event-demo/guests/G-1111-2222-3333-4444/validate')) return {ok:true,status:200,json:async()=>({status:'valid',presence:'outside',guest:{guest_number:'G-1111-2222-3333-4444'}})};
  return {ok:true,status:200,json:async()=>({status:'ok'})};
};
const c=new PulseXClient({baseUrl:'http://localhost:4310',fetchImpl:fakeFetch});
const u=await c.login('a@example.test','password-long-enough');
assert.equal(u.id,'u1');
assert.equal(c.csrf,'csrf-js');
assert.deepEqual(await c.adminSites(),{sites:[]});
assert.equal(calls[0].opts.method,'POST');
assert.deepEqual(await c.devices('agency-01'),{devices:[]});
const guest=await c.registerGuest('demo','0777000000',{name:'Guest'});
assert.equal(guest.guest_number,'G-1111-2222-3333-4444');
assert.equal((await c.publicGuest('demo',guest.guest_number)).status,'registered');
const manifest=await c.deviceGuestManifest('event-demo','device-secret-token');
assert.equal(manifest.guests.length,1);
const validated=await c.deviceValidateGuest('event-demo','G-1111-2222-3333-4444','device-secret-token');
assert.equal(validated.status,'valid');
const manifestCall=calls.find(x=>x.url.endsWith('/api/device/events/event-demo/guest-manifest'));
assert.equal(manifestCall.opts.headers['X-PulseX-Device-Token'],'device-secret-token');
console.log(JSON.stringify({status:'passed',checks:10}));
