import {api,toast,download} from './ui.mjs';
let dbPromise;
export function db(){return dbPromise??=new Promise((resolve,reject)=>{const r=indexedDB.open('pulsex-pilot-02',3);r.onupgradeneeded=()=>{for(const name of ['bundles','outbox','receipts','guests','guest_outbox','guest_receipts','guest_manifests','checkin_outbox','checkin_receipts','gate_presence'])if(!r.result.objectStoreNames.contains(name))r.result.createObjectStore(name,{keyPath:'id'});};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});}
export async function put(store,value){const d=await db();return new Promise((ok,no)=>{const tx=d.transaction(store,'readwrite');tx.objectStore(store).put(value);tx.oncomplete=()=>ok(value);tx.onerror=()=>no(tx.error);tx.onabort=()=>no(tx.error||new Error('LOCAL_SAVE_ABORTED'));});}
export async function get(store,id){const d=await db();return new Promise((ok,no)=>{const r=d.transaction(store).objectStore(store).get(id);r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error);});}
export async function del(store,id){const d=await db();return new Promise((ok,no)=>{const tx=d.transaction(store,'readwrite');tx.objectStore(store).delete(id);tx.oncomplete=()=>ok(true);tx.onerror=()=>no(tx.error);tx.onabort=()=>no(tx.error||new Error('LOCAL_DELETE_ABORTED'));});}
export async function all(store){const d=await db();return new Promise((ok,no)=>{const r=d.transaction(store).objectStore(store).getAll();r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error);});}
async function acknowledge(item,receipt){const d=await db();return new Promise((ok,no)=>{const tx=d.transaction(['outbox','receipts'],'readwrite');tx.objectStore('receipts').put({...receipt,at:new Date().toISOString()});if(['accepted','duplicate'].includes(receipt.status))tx.objectStore('outbox').delete(item.id);else tx.objectStore('outbox').put({...item,status:'rejected',error:receipt.error});tx.oncomplete=ok;tx.onerror=()=>no(tx.error);});}
let syncing;
export async function sync(){if(syncing)return syncing;syncing=(async()=>{try{let batch;do{batch=(await all('outbox')).filter(x=>x.status==='pending').slice(0,50);if(!batch.length)break;const out=await api('/api/collect',{items:batch.map(x=>x.envelope)});const receipts=new Map(out.receipts.map(r=>[r.id,r]));for(const item of batch){if(receipts.has(item.id))await acknowledge(item,receipts.get(item.id));}window.dispatchEvent(new Event('px-sync'));await deviceHeartbeat(true);if(!out.receipts.length)break;}while(batch.length===50);}catch{/* Keep every unacknowledged item; connectivity flags alone are not delivery proof. */}finally{syncing=null;window.dispatchEvent(new Event('px-sync'));}})();return syncing;}
export async function enqueue(envelope){await put('outbox',{id:envelope.id,status:'pending',envelope});window.dispatchEvent(new Event('px-sync'));await sync();const receipt=await get('receipts',envelope.id);return receipt||{id:envelope.id,status:'pending'};}
export async function bundle(slug){try{const b=await api('/api/public/site/'+encodeURIComponent(slug));await put('bundles',{id:slug,data:b,cached_at:new Date().toISOString()});return {...b,offline:false};}catch(e){if(e.status&&e.status<500)throw e;const x=await get('bundles',slug);if(!x)throw e;return {...x.data,offline:true,cached_at:x.cached_at};}}
export async function status(){const [xs,guests,checkins]=await Promise.all([all('outbox'),all('guest_outbox'),all('checkin_outbox')]);const count=(arr,state)=>arr.filter(x=>x.status===state).length;return{pending:count(xs,'pending')+count(guests,'pending')+count(checkins,'pending'),rejected:count(xs,'rejected')+count(guests,'rejected')+count(checkins,'rejected'),interaction_pending:count(xs,'pending'),guest_pending:count(guests,'pending'),checkin_pending:count(checkins,'pending'),items:xs,guest_items:guests,checkin_items:checkins};}
export async function prepare(b){if(!('serviceWorker'in navigator)||!window.isSecureContext)throw new Error('العمل دون اتصال يحتاج HTTPS أو localhost.');await navigator.serviceWorker.register('/sw.js');await navigator.serviceWorker.ready;let count=0;const missing=[];const cached=[];const slugs=[b.slug,...b.agencies.map(x=>x.slug),...(b.event?[b.event.slug]:[])];for(const slug of [...new Set(slugs)]){try{const x=await api('/api/public/site/'+slug);await put('bundles',{id:slug,data:x,cached_at:new Date().toISOString()});cached.push(x);}catch{missing.push(slug);}}
const cache=await caches.open('px-media-v02');const urls=new Set();for(const x of cached){for(const cfg of [x.config,x.event?.config].filter(Boolean)){for(const path of [cfg.logo,cfg.cover,...cfg.records.map(r=>r.media),...cfg.records.flatMap(r=>(r.options||[]).map(o=>o.media))].filter(Boolean))urls.add(path);}}
for(const u of urls){try{const full=new URL(u,location.origin);if(full.origin!==location.origin){missing.push(u);continue;}const r=await fetch(u,{cache:'reload'});if(!r.ok)throw new Error();await cache.put(u,r);count++;}catch{missing.push(u);}}
let persistent=false;try{persistent=await navigator.storage?.persist?.()||false;}catch{}
const ready={pages:cached.length,assets:count,missing,persistent,prepared_at:new Date().toISOString()};await put('bundles',{id:'ready:'+b.slug,data:ready});return ready;}
export async function saveDeviceToken(token,eventId=''){token=String(token||'').trim();if(token.length<20)throw new Error('رمز الجهاز غير صالح.');await put('bundles',{id:'device-auth',data:{token},cached_at:new Date().toISOString()});let prepared_guests=null;if(eventId&&navigator.onLine){try{const r=await fetch('/api/device/events/'+encodeURIComponent(eventId)+'/guest-manifest',{credentials:'same-origin',cache:'no-store',headers:{'X-PulseX-Device-Token':token}});if(r.ok){const data=await r.json();prepared_guests=(data.guests||[]).length;await put('guest_manifests',{id:eventId,data,cached_at:new Date().toISOString()});for(const guest of data.guests||[])await put('gate_presence',{id:eventId+':'+guest.guest_number,event_id:eventId,guest_number:guest.guest_number,state:guest.presence||'outside',updated_at:new Date().toISOString(),source:'manifest'});}}catch{}}return{paired:true,prepared_guests};}
export async function deviceHeartbeat(synced=false){const auth=await get('bundles','device-auth');const token=auth?.data?.token;if(!token)return{paired:false};const local=await status();try{const r=await fetch('/api/device/heartbeat',{method:'POST',credentials:'same-origin',cache:'no-store',headers:{'Content-Type':'application/json','X-PulseX-Device-Token':token},body:JSON.stringify({pending_count:local.pending,app_version:'0.9.0',synced,metadata:{kiosk:new URLSearchParams(location.search).get('kiosk')==='1',user_agent:navigator.userAgent.slice(0,300)}})});if(!r.ok)throw new Error('DEVICE_HEARTBEAT_FAILED');const data=await r.json();return{paired:true,...data};}catch(e){return{paired:true,offline:true,error:String(e?.message||e)};}}
export async function backup(){const [items,guestRaw,checkins]=await Promise.all([all('outbox'),all('guest_outbox'),all('checkin_outbox')]);const guest_registrations=guestRaw.map(item=>({...item,body:item.body?{...item.body,pass_token:item.body.pass_token?'[REDACTED]':undefined}:item.body}));download('pulsex-offline-pending.json',JSON.stringify({format:'pulsex-offline-v04-redacted',exported_at:new Date().toISOString(),sensitive_note:'Contains pending visitor data; guest pass possession secrets are redacted.',items,guest_registrations,checkins},null,2));}
export function activate(){if('serviceWorker'in navigator&&window.isSecureContext)navigator.serviceWorker.register('/sw.js').catch(()=>{});window.addEventListener('online',sync);setInterval(sync,6000);setInterval(()=>deviceHeartbeat(false),30000);sync();deviceHeartbeat(false);}
