import {icon} from './icons.mjs';
import {sectionsMeta,snippet,route,sectionLink,itemLink} from './catalog.mjs';
import{h,root,api,field,selectField,check,button,modal,toast,brand,media,msg,labels}from'./ui.mjs';
import{bundle,enqueue,prepare,status,backup,sync,activate,saveDeviceToken,deviceHeartbeat}from'./offline.mjs';
import{question,visible}from'./questions.mjs';
const params=new URLSearchParams(location.search);let page,preview=params.has('preview'),kiosk=params.get('kiosk')==='1',source=kiosk?'kiosk':params.get('source')==='qr'?'qr':'web';let visitor,session;const timers=[];
function identity(){const event=page.event_id||page.id;const key='px-visitor-'+event;if(kiosk){visitor=sessionStorage.getItem('px-kiosk-visitor')||crypto.randomUUID();sessionStorage.setItem('px-kiosk-visitor',visitor);}else{visitor=localStorage.getItem(key)||crypto.randomUUID();localStorage.setItem(key,visitor);}const sk='px-session-'+page.id;session=sessionStorage.getItem(sk)||crypto.randomUUID();sessionStorage.setItem(sk,session);}
export function pathFor(p){return p.kind==='platform'?'/':p.kind==='event'?'/e/'+p.slug:'/e/'+(p.event?.slug||'demo')+'/p/'+p.slug;}
async function send(kind,payload={},target=''){if(preview){toast('معاينة فقط — لم تُحفظ بيانات ولم تتغير نتائج الجمهور.');return{status:'preview'};}const envelope={id:crypto.randomUUID(),site_id:page.id,version:page.version,kind,visitor_id:visitor,session_id:session,source,target,payload,client_time:new Date().toISOString()};let r;
if(['profile','follow'].includes(kind)){if(!navigator.onLine)throw new Error('لا تُحفظ بيانات التواصل على التاب أثناء الانقطاع. أكمل التصفح دونها.');const out=await api('/api/collect',{items:[envelope]});r=out.receipts[0];}else r=await enqueue(envelope);
if(r.status==='rejected')throw new Error(r.error);if(!kind.startsWith('ad_'))toast(r.status==='pending'?'حُفظ على هذا الجهاز، وينتظر المزامنة.':'تم استلام مشاركتك. شكرًا لك!');return r;}
function welcome(){if(!page.config.welcome||preview||sessionStorage.getItem('welcomed-'+session))return;let step=0;const answers={};const content=h('div');const dialog=modal('أهلًا بك · الدخول متاح دون بيانات',content);const finish=()=>{sessionStorage.setItem('welcomed-'+session,'1');dialog.close();};function draw(){content.replaceChildren(h('p',{class:'muted'},'نرحّب بمشاركتك. كل البيانات التالية اختيارية، ويمكنك التخطي في أي وقت.'));if(step<3){const labels=[['phone','رقم الهاتف','tel'],['name','الاسم','text'],['job','العمل أو الجهة','text']];const[k,l,t]=labels[step];const f=field(l,t,answers[k]||'',{autocomplete:'off',maxlength:120});content.append(h('div',{class:'step-label'},`خطوة ${step+1} من 3 · اختيارية`),f.node,h('div',{class:'actions'},button('التالي',()=>{answers[k]=f.input.value;step++;draw();}),button('تخطي هذه الخطوة',()=>{step++;draw();},'btn secondary')),button('الدخول دون بيانات',finish,'text-btn'));}else{const consent=check('أوافق على مشاركة البيانات التي أدخلتها مع هذه الجهة للرد عليّ.');const marketing=check('أرغب باستقبال متابعة تسويقية — اختياري ومنفصل.');content.append(h('p',{},page.config.privacy),consent.node,marketing.node,h('div',{class:'actions'},button('حفظ البيانات والدخول',async()=>{if(!consent.input.checked)throw new Error('يمكنك الدخول دون بيانات، أو الموافقة على مشاركتها.');if(!Object.values(answers).some(Boolean)){finish();return;}await send('profile',{...answers,consent:true,marketing:marketing.input.checked});finish();}),button('الدخول دون حفظ',finish,'btn secondary')));}}draw();}
function feedback(target,title,criteria=page.config.rating_criteria||[]){
 const values={},body=h('div',{},h('p',{class:'muted'},'اختر تقييمًا أو اكتب ملاحظة. الملاحظات خاصة بالإدارة ولا تنشر تلقائيًا.'));
 for(const c of(criteria.length?criteria:[{key:'overall',label:'التقييم العام',weight:100}])){
  const row=h('div',{class:'rating-row'},h('strong',{},c.label));const stars=h('div',{class:'star-picker','aria-label':c.label});
  for(let i=1;i<=5;i++){const b=h('button',{type:'button',class:'star-choice','aria-label':`${i} من 5`,onclick:()=>{values[c.key]=i;for(const x of stars.children)x.classList.toggle('selected',Number(x.dataset.value)<=i);}},'★');b.dataset.value=String(i);stars.append(b);}row.append(stars);body.append(row);
 }
 const note=field('ملاحظة — اختيارية','textarea','',{maxlength:2000,placeholder:'ما الذي أعجبك؟ وما الذي يمكن تحسينه؟'});body.append(note.node);const d=modal('تقييم '+title,body);
 body.append(button('إرسال التقييم والملاحظة',async()=>{if(!Object.keys(values).length&&!note.input.value.trim())throw new Error('اختر تقييمًا أو اكتب ملاحظة أولًا.');await send('feedback',{rating:values.overall||null,criteria:values,note:note.input.value.trim()},target);d.close();}));
}
function contactForm(){const body=h('div',{},h('p',{class:'muted'},'اختر وسيلة مناسبة واترك ما يكفي فقط للتواصل معك.'));const fields={};for(const[k,l,t]of[['name','الاسم','text'],['phone','الهاتف','tel'],['email','البريد الإلكتروني','email'],['job','العمل / الجهة','text'],['message','كيف يمكننا مساعدتك؟','textarea']]){fields[k]=field(l,t);body.append(fields[k].node);}const preferred=selectField('أفضل وسيلة للتواصل',[['any','أي وسيلة متاحة'],['phone','اتصال هاتفي'],['whatsapp','واتساب'],['email','بريد إلكتروني']],'any');const consent=check('أوافق على مشاركة البيانات التي أدخلتها مع هذه الجهة لغرض التواصل فقط.');const marketing=check('أوافق بشكل منفصل على متابعة العروض والتحديثات.');const d=modal('طلب تواصل',body);body.append(preferred.node,consent.node,marketing.node,button('إرسال طلب التواصل',async()=>{if(!consent.input.checked)throw new Error('CONTACT_CONSENT_REQUIRED');if(!fields.phone.input.value&&!fields.email.input.value&&!fields.message.input.value)throw new Error('أدخل هاتفًا أو بريدًا أو رسالة حتى نعرف كيف نتواصل معك.');await send('follow',{...Object.fromEntries(Object.entries(fields).map(([k,f])=>[k,f.input.value])),preferred_channel:preferred.input.value,consent:true,marketing:marketing.input.checked});d.close();}));}
function card(r,scope=page.id){const c=h('article',{class:'card'},media(r),h('div',{class:'card-body'},r.tag?h('span',{class:'tag'},r.tag):null,h('h3',{},r.title),r.start?h('p',{class:'muted small'},new Date(r.start).toLocaleString('ar-YE')):null,h('p',{},r.body)));const actions=h('div',{class:'actions'},h('a',{class:'section-link',href:itemLink(scope,r.code)},'عرض التفاصيل',icon('arrow',17)));if(r.url)actions.append(h('a',{class:'text-btn',href:r.url,target:'_blank',rel:'noopener noreferrer'},'استعرض المزيد ←'));if(['participant','sponsor','session','place','service'].includes(r.kind))actions.append(button('قيّم / أضف ملاحظة',()=>feedback(scope+':'+r.code,r.title,page.config.rating_criteria||[]),'text-btn'));c.lastChild.append(actions);return c;}
const adSeen=new Set();let adObserver;
function ad(r){const c=h('aside',{class:'advert','data-ad':r.code},h('span',{class:'ad-label'},'إعلان'),media(r,'ad-media'),h('div',{},h('h3',{},r.title),h('p',{},r.body)));if(r.url)c.append(h('a',{class:'btn small',href:r.url,target:'_blank',rel:'noopener noreferrer',onclick:()=>send('ad_click',{},r.code).catch(()=>{})},'اكتشف العرض'));if(!preview){adObserver??=new IntersectionObserver(entries=>{for(const e of entries){if(!e.isIntersecting||e.intersectionRatio<.5)continue;const code=e.target.dataset.ad;if(adSeen.has(code))continue;const t=setTimeout(()=>{const rect=e.target.getBoundingClientRect();if(rect.top<innerHeight*.75&&rect.bottom>innerHeight*.25&&!document.hidden){adSeen.add(code);send('ad_view',{},code).catch(()=>{});}},1000);timers.push(t);}},{threshold:[.5]});adObserver.observe(c);}return c;}
function enabled(r){if(!r.enabled)return false;const t=Date.now();return(!r.start||Date.parse(r.start)<=t)&&(!r.end||Date.parse(r.end)>t);}
function facts(records){return h('div',{class:'facts-grid'},records.map(r=>{const cls='fact fact-'+(r.display||'number');const main=r.display==='text'?h('p',{class:'fact-text'},r.body):h('strong',{},r.value,h('small',{},' '+r.unit));const extra=(r.display==='bar'||r.display==='percentage'||r.display==='donut')?h('progress',{max:r.maximum||100,value:r.value,'aria-label':r.title}):r.display==='trend'?h('span',{class:'tag'},Number(r.value)>=0?'↑ اتجاه موجب':'↓ اتجاه سالب'):r.display==='comparison'?h('p',{class:'muted'},r.body||'أضف شرح المقارنة في الوصف'):r.display==='timeline'?h('p',{class:'muted'},r.body||'أضف مراحل الخط الزمني في الوصف'):null;return h('article',{class:cls},h('p',{},r.title),main,extra,h('small',{class:'muted'},'المصدر: '+(r.source||'لم يحدد')));}));}
function surveyBlock(records){
 const groups=Object.groupBy(records,r=>r.form_id),wrap=h('div',{class:'stack'}),surveyMap=Object.fromEntries((page.config.surveys||[]).map(s=>[s.id,s]));
 for(const[id,qsRaw]of Object.entries(groups)){
  const qs=qsRaw.sort((a,b)=>a.order-b.order),meta=surveyMap[id]||{id,title:'استبيان',description:'شاركنا رأيك.',completion:'شكرًا لك، تم استلام إجاباتك.',presentation:'one_page',show_progress:true,submit_label:'إرسال الاستبيان'},inputs={};
  const body=h('form',{class:'survey card survey-'+(meta.presentation||'one_page'),'data-form':id});
  const info=h('div',{class:'card-body'},h('span',{class:'eyebrow'},'استبيان'),h('h3',{},meta.title),meta.description?h('p',{class:'muted'},meta.description):null);
  const progressText=h('p',{class:'survey-progress'},`${qs.length} أسئلة · الحقول المعلّمة * مطلوبة`),progressBar=h('progress',{class:'survey-step-progress',max:Math.max(1,qs.length),value:1});if(meta.show_progress!==false)info.append(progressText,progressBar);body.append(info);
  let step=0;const questionHost=h('div',{class:'survey-question-host'});info.append(questionHost);
  function values(){return Object.fromEntries(Object.entries(inputs).map(([k,x])=>[k,x.get()]));}
  function visibleQuestions(){const vals=values();return qs.filter(q=>visible(q,vals));}
  function validateQuestion(q){const x=inputs[q.code],v=x.get();const missing=q.required&&(v===null||v===''||Array.isArray(v)&&!v.length);if(missing){x.node.classList.add('question-error');x.node.scrollIntoView({behavior:'smooth',block:'center'});toast('أكمل السؤال المطلوب أولًا.',true);return false;}x.node.classList.remove('question-error');return true;}
  function changed(){const vals=values();for(const q of qs)inputs[q.code].node.hidden=!visible(q,vals);if(meta.presentation==='stepper')drawStep();}
  for(const q of qs){const x=question(q,changed);inputs[q.code]=x;questionHost.append(x.node);}
  const controls=h('div',{class:'survey-controls'}),back=button('السابق',()=>{step=Math.max(0,step-1);drawStep();},'btn secondary'),next=button('التالي',()=>{const list=visibleQuestions();const q=list[step];if(q&&!validateQuestion(q))return;step=Math.min(list.length-1,step+1);drawStep();},'btn secondary'),submit=h('button',{type:'submit',class:'btn'},meta.submit_label||'إرسال الاستبيان');controls.append(back,next,submit);info.append(controls);
  function drawStep(){const list=visibleQuestions();if(!list.length)return;step=Math.max(0,Math.min(step,list.length-1));for(const q of qs)inputs[q.code].node.hidden=meta.presentation==='stepper'?q.code!==list[step].code:!visible(q,values());if(meta.presentation==='stepper'){back.hidden=step===0;next.hidden=step>=list.length-1;submit.hidden=step<list.length-1;if(meta.show_progress!==false){progressText.textContent=`السؤال ${step+1} من ${list.length}`;progressBar.max=list.length;progressBar.value=step+1;}}else{back.hidden=true;next.hidden=true;submit.hidden=false;if(meta.show_progress!==false){progressText.textContent=`${list.length} أسئلة · الحقول المعلّمة * مطلوبة`;progressBar.max=list.length;progressBar.value=list.length;}}}
  drawStep();
  body.addEventListener('submit',async ev=>{ev.preventDefault();submit.disabled=true;try{const visibleNow=visibleQuestions();const allowed=new Set(visibleNow.map(q=>q.code));const answers=Object.fromEntries(Object.entries(inputs).filter(([k])=>allowed.has(k)).map(([k,x])=>[k,x.get()]));const missing=visibleNow.filter(q=>q.required&&(answers[q.code]===null||answers[q.code]===''||Array.isArray(answers[q.code])&&!answers[q.code].length));if(missing.length){const idx=visibleNow.findIndex(q=>q.code===missing[0].code);if(meta.presentation==='stepper'&&idx>=0){step=idx;drawStep();}inputs[missing[0].code].node.classList.add('question-error');inputs[missing[0].code].node.scrollIntoView({behavior:'smooth',block:'center'});throw new Error('ANSWER_REQUIRED');}const r=await send('survey',{answers},id);if(r.status!=='preview')info.append(h('p',{class:'success'},r.status==='pending'?'حُفظت الإجابات محليًا وستُزامن عند عودة الاتصال.':meta.completion));}catch(e){toast(msg(e),true);}finally{submit.disabled=false;}});
  wrap.append(body);
 }
 return wrap;
}
function pollBlock(q){const box=h('article',{class:'card'}),body=h('div',{class:'card-body'},h('span',{class:'eyebrow'},'تصويت الجمهور'));const x=question(q);body.append(x.node,button('إرسال التصويت',async()=>{const answer=x.get();if(answer===null||answer===''||(Array.isArray(answer)&&!answer.length))throw new Error('اختر إجابة قبل إرسال التصويت.');if(!navigator.onLine)toast('التصويت غير المتصل معلّق، ولا يُحتسب إلا إن كان مفتوحًا عند المزامنة.');await send('poll',{answer},q.code);await refreshResults();}));if(q.show_results)body.append(h('div',{class:'poll-results','data-results':q.code},'النتائج المستلمة تظهر عند الاتصال.'));box.append(body);return box;}
async function refreshResults(){if(preview||!page)return;try{const x=await api('/api/public/site/'+page.slug+'/results');for(const[qcode,result]of Object.entries(x.polls)){const target=document.querySelector('[data-results="'+CSS.escape(qcode)+'"]');if(!target)continue;const q=page.config.records.find(x=>x.code===qcode);target.replaceChildren(h('small',{class:'muted'},`${result.ballots} أصوات مستلمة · نسخة ${x.version||page.version} · تحديث ${new Date(x.as_of).toLocaleTimeString('ar-YE')}`));for(const[k,n]of Object.entries(result.counts)){const title=q.options?.find(o=>o.key===k)?.label||k;target.append(h('div',{class:'result-row'},h('span',{},title),h('strong',{},n),h('progress',{max:Math.max(result.ballots,1),value:n,'aria-label':title})));}}}catch{for(const node of document.querySelectorAll('.poll-results'))node.replaceChildren(h('small',{class:'warning'},'النتائج غير متاحة الآن. لا تتحدث دون اتصال بالخادم.'));}}
function sectionContent(key){const records=page.config.records.filter(r=>r.enabled);const own=k=>records.filter(r=>r.kind===k).sort((a,b)=>a.order-b.order);const ecfg=page.event?.config||page.config;const eid=page.event?.id||page.id;const eventRecords=ecfg.records||[];
if(key==='event'){const fragment=h('div',{},h('p',{class:'lead'},ecfg.description),h('p',{class:'muted'},ecfg.location));if(ecfg.start)fragment.append(h('p',{class:'tag'},`${new Date(ecfg.start).toLocaleDateString('ar-YE')} — ${new Date(ecfg.end).toLocaleDateString('ar-YE')}`));const grid=h('div',{class:'grid three'});for(const agency of page.agencies){grid.append(h('article',{class:'card mini'},h('span',{class:'entity-icon',style:'--accent:'+agency.primary},agency.title.slice(-2)),h('h3',{},agency.title),h('p',{class:'muted'},agency.subtitle),h('a',{class:'text-btn',href:'/e/'+(page.event?.slug||page.slug)+'/p/'+agency.slug},'زيارة صفحة الجهة ←'),agency.participation?.booth?h('span',{class:'tag'},'الجناح '+agency.participation.booth):null,button('تقييم الجهة',()=>feedback(agency.id+':general',agency.title,agency.rating_criteria||[]),'text-btn')));}fragment.append(h('h3',{},'الجهات المشاركة'),grid);for(const[k,label]of[['participant','دليل المشاركين الإضافي'],['sponsor','الرعاة'],['session','البرنامج والأحداث'],['place','المكان والأجنحة'],['news','آخر المستجدات']]){const list=eventRecords.filter(r=>r.kind===k&&r.enabled);if(list.length)fragment.append(h('h3',{class:'subheading'},label),h('div',{class:'grid'},list.map(r=>card(r,eid))));}fragment.append(button('تقييم عام للفعالية',()=>feedback(eid+':general',ecfg.title,ecfg.rating_criteria||[]),'btn secondary'));return fragment;}
if(key==='facts')return facts(own('fact'));
if(key==='about')return h('div',{class:'about-block'},h('p',{class:'lead'},page.config.description),page.config.cover?h('img',{src:page.config.cover,alt:page.config.title,class:'about-image'}):null);
if(key==='services')return h('div',{class:'grid'},own('service').map(r=>card(r)));
if(key==='questions')return surveyBlock(own('question'));
if(key==='polls')return h('div',{class:'grid'},own('poll').map(pollBlock));
if(key==='ratings')return h('div',{class:'rating-cta'},h('div',{},h('h3',{},'كيف كانت تجربتك؟'),h('p',{},'تقييم مستقل للجهة أو ملاحظة عامة. صوتك يساعدنا على التحسين.')),button('قيّم الزيارة',()=>feedback(page.id+':general',page.config.title,page.config.rating_criteria||[])));
if(key==='contact')return h('div',{},h('div',{class:'grid'},own('contact').map(r=>card(r))),h('div',{class:'card contact-cta'},h('div',{class:'card-body'},h('h3',{},'تحتاج تواصلًا مباشرًا؟'),h('p',{class:'muted'},'اترك وسيلة التواصل المناسبة أو رسالة قصيرة. لا تحتاج إلى إنشاء حساب.'),button('إرسال طلب تواصل',contactForm))));
if(key==='offers')return h('div',{},h('div',{class:'grid'},own('offer').map(r=>card(r))),...own('ad').filter(enabled).map(ad));
if(key==='media')return h('div',{class:'grid'},own('media').map(r=>card(r)));
return h('div');}
async function connectionBar(){const b=document.getElementById('connection-status');if(!b)return;const s=await status();b.textContent=(navigator.onLine?'اتصال متاح':'دون اتصال')+` · ${s.pending} بانتظار المزامنة`+(s.rejected?` · ${s.rejected} يحتاج مراجعة`:'');b.className=s.pending||s.rejected?'connection warning':'connection';}
async function offlinePanel(){const s=await status();const token=field('رمز ربط الطرفية — من لوحة الإدارة','password','',{autocomplete:'off'});const pairState=h('div');const body=h('div',{},h('p',{},'جهّز الصفحة قبل فصل الإنترنت. لا تحذف بيانات المتصفح، ولا تستخدم التصفح الخفي.'),h('p',{class:'muted'},'المحتوى المحمّل يستمر على الجهاز. النتائج العامة والتحديثات تحتاج اتصالًا.'),h('div',{class:'card mini'},h('h3',{},'ربط هذه الطرفية'),h('p',{class:'muted small'},'أنشئ الطرفية من الإدارة ← الأجهزة والطرفيات، ثم الصق الرمز الذي يظهر مرة واحدة.'),token.node,button('حفظ الرمز واختبار الربط',async()=>{await saveDeviceToken(token.input.value);const x=await deviceHeartbeat(false);pairState.replaceChildren(h('div',{class:'notice'},x.paired&&!x.offline?'تم ربط الطرفية وإرسال نبضة التشغيل.':'حُفظ الرمز، لكن الخادم غير متاح الآن.'));}),pairState),h('div',{class:'actions'},button('تحميل صفحات الفعالية ووسائطها',async()=>{const result=await prepare(page);body.append(h('div',{class:'notice'},`تم حفظ ${result.pages} صفحة و${result.assets} ملفات. غير المتاح: ${result.missing.length}. تخزين مستمر: ${result.persistent?'مسموح':'غير مضمون'}.`));if(result.missing.length)body.append(h('pre',{},result.missing.join('\n')));}),button('مزامنة الآن',async()=>{await sync();await connectionBar();toast('تمت محاولة المزامنة. راجع عدد المعلّق.');},'btn secondary')));if(s.rejected)body.append(h('h3',{},'طلبات غير محتسبة تحتاج مراجعة'),h('ul',{},s.items.filter(x=>x.status==='rejected').map(x=>h('li',{},x.id+' — '+x.error))));modal('حالة الجهاز والعمل دون اتصال',body,true);}
function resetKiosk(){sessionStorage.removeItem('px-kiosk-visitor');sessionStorage.removeItem('px-session-'+page.id);location.reload();}
async function requestAccess(){const role=selectField('أريد الانضمام كـ',[['organizer','جهة منظمة لفعالية'],['participant','جهة مشاركة في فعالية'] ],page.kind==='event'?'participant':'organizer'),org=field('اسم الجهة / المؤسسة'),name=field('اسم مسؤول التواصل'),email=field('البريد','email'),phone=field('الهاتف','tel'),ptype=selectField('نوع المشاركة',[['exhibitor','عارض'],['sponsor','راعٍ'],['partner','شريك'],['speaker','متحدث/جهة'],['media','إعلام'],['vendor','مزود']],'exhibitor'),account=check('أحتاج حساب تحكم للجهة',true),message=field('ملاحظات أو تعريف مختصر','textarea');const body=h('div',{},h('p',{class:'muted'},'الزائر لا يحتاج حسابًا. الجهات تستطيع طلب الانضمام من الموقع العام؛ الطلب يخضع للاعتماد. يمكن أن تكون الجهة للعرض فقط أو تحصل على حساب تحكم بكلمة مرور مؤقتة تُغيّر لاحقًا.'),role.node,org.node,name.node,email.node,phone.node,ptype.node,account.node,message.node);role.input.addEventListener('change',()=>{ptype.node.hidden=role.input.value!=='participant';});ptype.node.hidden=role.input.value!=='participant';const d=modal('الانضمام إلى PulseX',body);body.append(button('إرسال طلب الانضمام',async()=>{await api('/api/signup-request',{site_id:page.id,requested_role:role.input.value,organization_name:org.input.value,contact_name:name.input.value,email:email.input.value,phone:phone.input.value,participation_type:ptype.input.value,wants_account:account.input.checked,message:message.input.value});toast('تم استلام الطلب للمراجعة. لا توجد صلاحية قبل الاعتماد.');d.close();}));}
// Open landing sections, full section routes and item routes share this exact renderer.
let mainHost;
const sectionKinds={facts:['fact'],services:['service'],questions:['question'],polls:['poll'],offers:['offer','ad'],media:['media'],contact:['contact']};
const sectionForKind={service:'services',question:'questions',poll:'polls',fact:'facts',offer:'offers',ad:'offers',media:'media',contact:'contact',news:'event',participant:'event',sponsor:'event',session:'event',place:'event'};
function enabledSections(){return page.config.sections.filter(s=>s.enabled).sort((a,b)=>a.order-b.order);}
function recordsOf(kind,config=page.config){return(config.records||[]).filter(r=>r.enabled&&r.kind===kind).sort((a,b)=>a.order-b.order);}
function fullLink(key,label='استعرض القسم كاملًا'){return h('a',{class:'section-link',href:sectionLink(key)},label,icon('arrow',19));}
function publicAgencyLink(a){return '/e/'+(page.event?.slug||page.slug)+'/p/'+a.slug;}
function agencyCard(a){return h('article',{class:'card agency-card'},h('a',{href:publicAgencyLink(a),class:'entity-link'},h('span',{class:'entity-icon',style:'--accent:'+a.primary},icon('building',28)),h('h3',{},a.title),h('p',{class:'muted'},snippet(a.subtitle,90)),h('span',{class:'section-link'},'زيارة صفحة الجهة',icon('arrow',18))));}
function browseCard(r,scope=page.id){return h('article',{class:'card browse-card'},h('a',{href:itemLink(scope,r.code),class:'card-cover-link'},media(r),h('div',{class:'card-body'},h('span',{class:'tag'},r.tag||labels[r.kind]||'اكتشف'),h('h3',{},r.title),h('p',{class:'muted'},snippet(r.body)||'افتح التفاصيل لاستعراض المحتوى والمشاركة.'),h('span',{class:'section-link'},'اكتشف التفاصيل',icon('arrow',18)))));}
function emptySection(key){return h('div',{class:'empty-content'},icon(sectionsMeta[key]?.icon||'spark',26),h('div',{},h('strong',{},'المحتوى قيد التجهيز'),h('p',{class:'muted'},'لم تُنشر مواد في هذا القسم بعد. يمكنك استكشاف بقية الصفحة.')));}
function dateText(value){if(!value)return 'يُعلن الموعد لاحقًا';const d=new Date(value);return Number.isNaN(d.valueOf())?'موعد غير محدد':d.toLocaleDateString('ar-YE',{day:'numeric',month:'long',year:'numeric'});}
function eventCards(items){return h('div',{class:'grid three'},items.map(e=>h('article',{class:'card event-card'},e.cover?h('img',{src:e.cover,alt:e.title,class:'record-media'}):h('div',{class:'event-placeholder'},icon('calendar',42)),h('div',{class:'card-body'},h('div',{class:'between'},h('span',{class:'tag status-'+(e.status||'current')},e.status==='upcoming'?'قادمة':e.status==='completed'?'منتهية':'جارية / متاحة'),h('small',{class:'muted'},dateText(e.start))),h('h3',{},e.title),h('p',{class:'muted'},snippet(e.subtitle)),h('a',{class:'section-link',href:'/e/'+e.slug},'زيارة موقع الفعالية',icon('arrow',18))))));}
function sectionConfig(key){return (page.config.sections||[]).find(s=>s.key===key)||{key,layout:'cards',preview_count:3};}
function previewLimit(key){const n=Number(sectionConfig(key).preview_count||3);return Math.max(1,Math.min(6,n));}
function previewGrid(key,children){return h('div',{class:'grid three section-grid layout-'+(sectionConfig(key).layout||'cards')},children);}
function previewContent(key){
  const meta=sectionsMeta[key]||{};
  if(key==='event'){
    const ecfg=page.event?.config||page.config;const scope=page.event?.id||page.id;
    const body=h('div',{},h('div',{class:'event-summary'},h('div',{},h('span',{class:'tag'},icon('calendar',16),dateText(ecfg.start)),h('h3',{},ecfg.title),h('p',{class:'muted'},snippet(ecfg.description,200))),h('div',{class:'event-stats'},h('strong',{},page.agencies.length),h('span',{},'صفحات جهات متاحة'))),previewGrid('event',page.agencies.slice(0,previewLimit('event')).map(agencyCard)));
    const shared=(ecfg.records||[]).filter(r=>r.enabled&&['sponsor','session','place'].includes(r.kind)).slice(0,previewLimit('event'));
    if(shared.length)body.append(previewGrid('event',shared.map(r=>browseCard(r,scope))));
    return body;
  }
  if(key==='about')return h('div',{class:'about-preview'},h('div',{},h('h3',{},page.config.subtitle||page.config.title),h('p',{class:'lead'},snippet(page.config.description,330)),fullLink('about','تعرّف علينا أكثر')),h('div',{class:'about-promise'},icon('spark',36),h('strong',{},'معًا نصنع تجربة أقرب'),h('p',{},'استكشف خدماتنا، شارك برأيك، وتواصل معنا بطريقتك.')));
  if(key==='facts'){const rs=recordsOf('fact');return rs.length?facts(rs.slice(0,previewLimit('facts'))):emptySection(key);}
  if(key==='questions'){
    const qs=recordsOf('question');const groups={};for(const q of qs)(groups[q.form_id]??=[]).push(q);
    return qs.length?previewGrid('questions',Object.entries(groups).slice(0,previewLimit('questions')).map(([id,list])=>h('article',{class:'card engagement-card'},h('span',{class:'surface-icon'},icon('message',28)),h('span',{class:'tag'},list.length+' أسئلة · '+id),h('h3',{},list[0].title),h('p',{class:'muted'},'اختيارات وتقييمات وآراء. الاسم والهاتف ليسا شرطًا للمشاركة.'),h('a',{class:'btn',href:itemLink(page.id,list[0].code)},'ابدأ الاستبيان',icon('arrow',18))))):emptySection(key);
  }
  if(key==='polls'){const rs=recordsOf('poll');return rs.length?previewGrid('polls',rs.slice(0,previewLimit('polls')).map(r=>h('article',{class:'card engagement-card'},h('span',{class:'surface-icon'},icon('chart',28)),h('span',{class:'tag'},r.status==='open'?'تصويت متاح':'التصويت مغلق'),h('h3',{},r.title),h('p',{class:'muted'},r.options?.length?r.options.length+' خيارات · شارك باختيارك':'شارك بتقييمك'),h('a',{class:'btn',href:itemLink(page.id,r.code)},r.status==='open'?'شارك في التصويت':'استعرض التصويت',icon('arrow',18))))):emptySection(key);}
  if(key==='ratings')return h('div',{class:'rating-cta'},h('div',{},h('div',{class:'stars','aria-hidden':'true'},'☆ ☆ ☆ ☆ ☆'),h('h3',{},'تجربتك تهمّنا. كيف كانت زيارتك؟'),h('p',{},'تقييم مستقل أو ملاحظة خاصة، دون نشر بياناتك للجمهور.')),h('a',{href:sectionLink(key),class:'btn'},'شارك تقييمك',icon('star',18)));
  const rs=(page.config.records||[]).filter(r=>r.enabled&&(sectionKinds[key]||[]).includes(r.kind)&&(r.kind!=='ad'||enabled(r))).sort((a,b)=>a.order-b.order);
  if(key==='contact'&&!rs.length)return h('div',{class:'rating-cta'},h('p',{},'اترك وسيلة تواصل اختيارية ليعود فريق الجهة إليك.'),h('a',{href:sectionLink(key),class:'btn'},'تواصل معنا'));
  return rs.length?previewGrid(key,rs.slice(0,previewLimit(key)).map(r=>browseCard(r))):emptySection(key);
}
function sectionShell(key,title,index,content){const meta=sectionsMeta[key]||{},sc=sectionConfig(key);return h('section',{id:key,class:'section landing-section section-layout-'+(sc.layout||'cards'),'data-section':key},h('div',{class:'section-heading'},h('div',{class:'heading-copy'},h('span',{class:'eyebrow'},meta.eyebrow||'EXPLORE'),h('h2',{},title),h('p',{class:'section-description'},meta.description||'')),fullLink(key)),content);}
function renderHome(){
  if(page.kind==='platform'){
    const current=(page.events||[]).filter(e=>e.status==='current'),upcoming=(page.events||[]).filter(e=>e.status==='upcoming'),completed=(page.events||[]).filter(e=>e.status==='completed');
    mainHost.append(sectionShell('events','الفعاليات الجارية والقادمة',1,h('div',{},current.length?h('div',{},h('h3',{},'تجري الآن'),eventCards(current)):null,upcoming.length?h('div',{},h('h3',{class:'subheading'},'القادمة'),eventCards(upcoming)):null,completed.length?h('div',{},h('h3',{class:'subheading'},'ما تم إنجازه'),eventCards(completed)):null)));
    mainHost.append(h('section',{class:'section join-section',id:'join'},h('div',{class:'join-panel'},h('span',{class:'eyebrow'},'JOIN PULSEX'),h('h2',{},'هل تمثل جهة أو تنظّم فعالية؟'),h('p',{},'قدّم طلب حساب من الموقع العام. الطلب لا يمنح صلاحية تلقائيًا؛ يراجعه مدير المنصة ثم تُنشأ عضوية المؤسسة أو مشاركة الفعالية.'),button('طلب اشتراك / حساب',requestAccess,'btn'),h('a',{href:'/admin',class:'btn secondary'},'لدي حساب بالفعل'))));
    mainHost.append(sectionShell('about','منصة واحدة. تجارب متصلة.',2,previewContent('about')));mainHost.append(sectionShell('facts','حقائق تنشرها المنصة',3,previewContent('facts')));
    const ns=recordsOf('news');mainHost.append(sectionShell('news','مستجدات وقصص من التجربة',4,ns.length?h('div',{class:'grid three'},ns.slice(0,3).map(r=>browseCard(r))):emptySection('news')));return;
  }
  let idx=0;for(const s of enabledSections()){
    mainHost.append(sectionShell(s.key,s.title,++idx,previewContent(s.key)));
    // A campaign targeted to "all" is inserted once, not ten copies on one page.
    const ads=recordsOf('ad').filter(r=>enabled(r)&&(r.placement===s.key||(r.placement==='all'&&idx===3))).slice(0,2);
    if(ads.length)mainHost.append(h('div',{class:'ad-break'},ads.map(ad)));
  }
}
function resolveItem(scope,code){let config;if(scope===page.id)config=page.config;else if(scope===page.event?.id)config=page.event.config;else return null;return(config.records||[]).find(r=>r.code===code&&r.enabled&&(r.kind!=='ad'||enabled(r)));}
function recordDetail(r,scope){
  if(r.kind==='question')return surveyBlock(recordsOf('question').filter(q=>q.form_id===r.form_id));
  if(r.kind==='poll')return pollBlock(r);
  if(r.kind==='fact')return facts([r]);
  if(r.kind==='ad')return ad(r);
  const content=h('article',{class:'detail-article'},media(r,'detail-media'),h('div',{class:'detail-copy'},h('span',{class:'tag'},r.tag||labels[r.kind]),r.start?h('p',{class:'muted'},dateText(r.start)+(r.end?' — '+dateText(r.end):'')):null,h('p',{class:'lead preserve-lines'},r.body||'لا توجد تفاصيل إضافية منشورة.'),h('div',{class:'actions'},r.url?h('a',{href:r.url,class:'btn',target:'_blank',rel:'noopener noreferrer'},'الموقع أو الرابط المرتبط',icon('arrow',18)):null,['participant','sponsor','session','place','service'].includes(r.kind)?button('قيّم / أضف ملاحظة',()=>feedback(scope+':'+r.code,r.title,page.config.rating_criteria||[]),'btn secondary'):null)));
  return content;
}
function fullSection(key){
  if(page.kind==='platform'){
    if(key==='events')return eventCards(page.events||[]);
    if(key==='news')return h('div',{class:'grid three'},recordsOf('news').map(r=>card(r)));
  }
  const content=sectionContent(key);return content.textContent.trim()||content.querySelector('img,video')?content:emptySection(key);
}
function renderRoute(scroll=true){
  adObserver?.disconnect();
  const state=route(location.hash);const validKeys=page.kind==='platform'?['events','about','facts','news']:enabledSections().map(s=>s.key);
  mainHost.replaceChildren();const hero=document.querySelector('.hero');hero.hidden=state.type!=='home';
  document.querySelectorAll('[data-nav-key]').forEach(a=>a.setAttribute('aria-current',state.type==='section'&&a.dataset.navKey===state.key?'page':'false'));
  if(state.type==='home')renderHome();
  else{
    let title='',content=null,back='';
    if(state.type==='section'&&validKeys.includes(state.key)){title=page.kind==='platform'?({events:'الفعاليات والتجارب',about:'عن المنصة',facts:'الحقائق والأرقام',news:'المستجدات والنتائج المنشورة'})[state.key]:enabledSections().find(s=>s.key===state.key).title;content=fullSection(state.key);}
    if(state.type==='item'){
      const item=resolveItem(state.scope,state.code);const key=item?(page.kind==='platform'&&item.kind==='news'?'news':sectionForKind[item.kind]):'';
      if(item&&validKeys.includes(key)){title=item.kind==='question'?'الاستبيان · '+item.form_id:item.title;content=recordDetail(item,state.scope);back=key;}
    }
    if(!content){title='هذا المحتوى غير متاح';content=h('div',{class:'empty-content'},h('p',{},'ربما أُخفي القسم أو لم تُنشر المادة. يمكنك العودة واستكشاف الأقسام المتاحة.'));}
    mainHost.append(h('nav',{class:'breadcrumb','aria-label':'مسار الصفحة'},h('a',{href:'#'},'الرئيسية'),h('span',{},' / '),back?h('a',{href:sectionLink(back)},page.config.sections.find(s=>s.key===back)?.title||'القسم'):null,h('span',{},title)),h('section',{class:'section detail-section'},h('div',{class:'section-heading'},h('div',{},h('span',{class:'eyebrow'},'EXPLORE THE DETAILS'),h('h1',{tabindex:'-1'},title)),h('a',{class:'btn secondary',href:back?sectionLink(back):'#'},back?'العودة إلى القسم':'كل الأقسام')),content));
  }
  if(scroll){window.scrollTo({top:0,behavior:'instant'});if(state.type!=='home')mainHost.querySelector('h1')?.focus({preventScroll:true});}
  refreshResults();
}
function brandLiveLayer(){
  const tpl=page?.config?.template||'';
  if(!['rts_tech','easy_finance','tharawat_finance'].includes(tpl))return null;
  const records=(page.config.records||[]).filter(enabled);
  const facts=records.filter(r=>r.kind==='fact').slice(0,3);
  const services=records.filter(r=>r.kind==='service').slice(0,4);
  const activePolls=records.filter(r=>r.kind==='poll'&&r.status==='open');
  if(tpl==='rts_tech'){
    return h('section',{class:'brand-live rts-live','aria-label':'RTS live experience'},
      h('div',{class:'brand-live-status'},h('span',{class:'live-signal'}),h('strong',{},'RTS LIVE SYSTEM'),h('small',{},page.offline?'OFFLINE READY':'CONNECTED EXPERIENCE')),
      h('div',{class:'live-metrics'},
        h('div',{},h('small',{},'CAPABILITIES'),h('strong',{},String(services.length||records.filter(r=>['service','media'].includes(r.kind)).length).padStart(2,'0'))),
        h('div',{},h('small',{},'LIVE POLLS'),h('strong',{},String(activePolls.length).padStart(2,'0'))),
        h('div',{},h('small',{},'INTERACTIONS'),h('strong',{},String(records.filter(r=>['question','poll','rating'].includes(r.kind)).length).padStart(2,'0')))),
      h('a',{href:services[0]?itemLink(page.id,services[0].code):sectionLink('services'),class:'brand-live-action'},'ENTER EXPERIENCE',icon('arrow',18)));
  }
  if(tpl==='easy_finance'){
    return h('section',{class:'brand-live easy-live','aria-label':'Easy live experience'},
      h('div',{class:'easy-live-copy'},h('span',{class:'live-signal'}),h('div',{},h('strong',{},'Easy · explore in one tap'),h('small',{},page.offline?'المحتوى جاهز على هذا الجهاز':'تجربة متصلة وتتحدث مع تفاعلك'))),
      h('div',{class:'easy-live-rail'},(services.length?services:records.filter(r=>['offer','fact'].includes(r.kind)).slice(0,4)).map((r,i)=>h('a',{href:itemLink(page.id,r.code),class:'easy-live-chip'},h('span',{},String(i+1).padStart(2,'0')),h('strong',{},r.title)))),
      activePolls[0]?h('a',{href:itemLink(page.id,activePolls[0].code),class:'brand-live-action'},'صوّت الآن',icon('arrow',18)):null);
  }
  const insights=[...facts,...records.filter(r=>['news','offer'].includes(r.kind))].slice(0,4);
  return h('section',{class:'brand-live tharawat-live','aria-label':'Tharawat live experience'},
    h('div',{class:'tharawat-live-title'},h('span',{class:'eyebrow'},'THARAWAT · LIVE PERSPECTIVE'),h('strong',{},'المعلومة تتحول إلى تجربة قابلة للاستكشاف')),
    h('div',{class:'tharawat-live-ticker'},(insights.length?insights:[{title:'اكتشف المحتوى والتجربة',value:'•'}]).map(r=>h('a',{href:r.code?itemLink(page.id,r.code):'#about',class:'tharawat-tick'},h('small',{},r.kind==='fact'?'INSIGHT':'DISCOVER'),h('strong',{},r.kind==='fact'?String(r.value)+(r.unit?' '+r.unit:''):r.title),r.kind==='fact'?h('span',{},r.title):null))),
    h('span',{class:'tharawat-live-mark'},'ث'));
}

export async function publicPage(slug){
  page=preview?await api('/api/admin/sites/'+params.get('preview')+'/preview'):await bundle(slug);identity();document.title=page.config.title+' | PulseX';document.documentElement.style.setProperty('--accent',page.config.primary);document.documentElement.style.setProperty('--secondary',page.config.secondary||'#0F3D46');document.documentElement.style.setProperty('--theme-accent',page.config.accent||page.config.primary);document.documentElement.style.setProperty('--page-bg',page.config.background||'#F5F8FA');document.documentElement.style.setProperty('--surface',page.config.surface||'#FFFFFF');document.documentElement.style.setProperty('--text-color',page.config.text_color||'#17313B');document.documentElement.style.setProperty('--radius',String(page.config.radius||22)+'px');document.body.dataset.template=page.config.template||'fintech';document.body.dataset.cards=page.config.card_style||'soft';document.body.dataset.hero=page.config.hero_style||'split';document.body.dataset.font=page.config.font||'system';document.body.dataset.buttons=page.config.button_style||'rounded';document.body.dataset.nav=page.config.nav_style||'clean';document.body.dataset.density=page.config.density||'comfortable';document.body.dataset.width=page.config.content_width||'wide';document.body.dataset.headings=page.config.heading_scale||'balanced';root.replaceChildren();document.body.classList.add('public-site');
  const home=pathFor(page);const publicMark=(page.config.title||'PulseX').trim().slice(0,1).toUpperCase()||'P';const header=h('header',{class:'topbar site-topbar'},h('div',{class:'topbar-inner'},brand(page.config.title||'PulseX',publicMark,home),h('nav',{class:'toplinks','aria-label':'التنقل العام'},h('a',{href:'/'},'المنصة'),page.event?h('a',{href:'/e/'+page.event.slug},'موقع المعرض'):null,h('a',{href:'#about'},'عن الصفحة'),h('a',{href:'/admin',class:'studio-link'},icon('layers',17),'دخول الإدارة')),button(page.kind==='platform'?'اشترك / طلب حساب':'طلب حساب',requestAccess,'btn secondary small')));root.append(h('a',{href:'#main-content',class:'skip-link'},'انتقل إلى المحتوى'),header);
  if(preview)root.append(h('div',{class:'preview-banner'},'وضع المعاينة · نسخة المسودة · لا تُسجل أصوات أو إحصائيات'));
  root.append(h('div',{class:'pilot-note'},h('span',{class:'status-dot'}),'بيئة تجربة · المحتوى النموذجي توضيحي، وليس بيانات حضور فعلية'));
  if(page.offline)root.append(h('div',{class:'notice offline-notice'},'تصفح نسخة محفوظة على الجهاز · آخر تنزيل: '+new Date(page.cached_at).toLocaleString('ar-YE')+' · النتائج والتحديثات تحتاج اتصالًا.'));
  const c=page.config;const guestEventSlug=page.kind==='event'?page.slug:page.event?.slug||'';
  const keys=page.kind==='platform'?[{key:'events',title:'الفعاليات'},{key:'about',title:'عن المنصة'},{key:'facts',title:'الحقائق'},{key:'news',title:'المستجدات'}]:enabledSections();
  const primary=page.kind==='platform'?'events':keys.some(s=>s.key==='services')?'services':keys[0]?.key;
  const second=keys.some(s=>s.key==='questions')?'questions':page.kind==='platform'?'about':keys[1]?.key;
  const heroText=h('div',{class:'hero-content'},h('span',{class:'hero-kicker'},icon('spark',17),page.kind==='platform'?'منصة للتجارب التي تترك أثرًا':page.kind==='event'?'الفعالية · المعرفة · التجربة':'تعرف علينا. استكشف. وشاركنا رأيك.'),c.logo?h('img',{src:c.logo,alt:'شعار '+c.title,class:'site-logo'}):null,h('h1',{},c.title),h('p',{class:'hero-subtitle'},c.subtitle),h('p',{class:'hero-description'},snippet(c.description,185)),h('div',{class:'actions'},primary?h('a',{href:sectionLink(primary),class:'btn'},page.kind==='platform'?'استكشف الفعاليات':'اكتشف ما نقدمه',icon('arrow',19)):null,second?h('a',{href:sectionLink(second),class:'btn hero-secondary'},second==='questions'?'شاركنا رأيك':'تعرّف أكثر'):null,guestEventSlug?h('a',{href:'/e/'+guestEventSlug+'/guest',class:'btn hero-secondary'},'بطاقة الزائر'):null),h('div',{class:'hero-assurances'},h('span',{},icon('check',16),'تصفح بحرية'),h('span',{},icon('shield',16),'البيانات الشخصية اختيارية')));
  const stage=h('div',{class:'hero-art'},h('div',{class:'visual-grid'}),h('div',{class:'visual-disc'}),c.cover?h('img',{src:c.cover,alt:'المحتوى التعريفي للصفحة',class:'hero-picture'}):h('div',{class:'hero-logo'},icon('spark',92)),h('div',{class:'float-card float-top'},h('span',{class:'surface-icon'},icon('layers',21)),h('div',{},h('strong',{},keys.length+' أقسام قابلة للاستكشاف'),h('small',{},'محتوى مرتبط بمدخلات الجهة'))),h('div',{class:'float-card float-bottom'},h('span',{class:'surface-icon'},icon('message',21)),h('div',{},h('strong',{},'رأيك يصنع فرقًا'),h('small',{},'أسئلة وتصويت وتقييم اختياري'))));
  root.append(h('section',{class:'hero'},heroText,stage));
  const liveLayer=brandLiveLayer();if(liveLayer)root.append(liveLayer);
  const nav=h('nav',{class:'section-nav site-section-nav','aria-label':'أقسام الصفحة'},keys.map(s=>h('a',{href:'#'+s.key,'data-nav-key':s.key},icon(sectionsMeta[s.key]?.icon||'spark',17),s.title)));
  root.append(nav);mainHost=h('main',{class:'public-main',id:'main-content'});root.append(mainHost);renderRoute(false);window.addEventListener('hashchange',()=>{const r=route(location.hash);renderRoute(r.type!=='home');if(r.type==='home'&&r.anchor)requestAnimationFrame(()=>document.getElementById(r.anchor)?.scrollIntoView({behavior:'smooth',block:'start'}));});
  const floating=h('div',{class:'devicebar'},button('تجهيز دون إنترنت',offlinePanel,'text-btn'),h('span',{id:'connection-status',class:'connection'},'جارٍ فحص المزامنة'),kiosk?button('زائر جديد',resetKiosk,'btn small'):button('وضع التاب',()=>{const u=new URL(location.href);u.searchParams.set('kiosk','1');location.href=u.href;},'text-btn'));
  root.append(h('section',{class:'closing-cta'},h('div',{},h('span',{class:'eyebrow'},'EXPERIENCES THAT CONNECT'),h('h2',{},'كل مشاركة بداية لفكرة جديدة.'),h('p',{},'استكشف المحتوى أو شارك برأيك. أنت تختار طريقة تفاعلك.')),h('a',{href:second?sectionLink(second):'#',class:'btn'},'استكشف التجربة',icon('arrow',18))),floating,h('footer',{class:'footer'},h('div',{},brand(page.config.title||'PulseX',publicMark,home),h('p',{},'تجربة تصنعها الجهة، ورأي يترك أثرًا.'),page.kind!=='platform'?h('small',{class:'platform-attribution'},'Powered by PulseX · Live Experience Platform'):null),h('nav',{},h('a',{href:'/'},'المنصة'),h('a',{href:'/admin'},'الإدارة'),button('طلب حساب للجهة',requestAccess,'text-btn'),button('الخصوصية والموافقة',()=>modal('الخصوصية والموافقة',h('div',{},h('p',{},page.config.privacy),h('p',{},'يمكن تصفح المحتوى والتفاعل دون إدخال الاسم والهاتف. الموافقة على المتابعة منفصلة.'))),'text-btn')),h('small',{},'PulseX · Windows 10 Role & Template Candidate')));
  window.addEventListener('px-sync',connectionBar);window.addEventListener('online',connectionBar);window.addEventListener('offline',connectionBar);await connectionBar();activate();if(!preview&&page.kind!=='platform'){const visitKey='visited-'+page.id+'-'+session;if(!sessionStorage.getItem(visitKey)){await enqueue({id:crypto.randomUUID(),site_id:page.id,version:page.version,kind:'visit',visitor_id:visitor,session_id:session,source,target:'',payload:{},client_time:new Date().toISOString()});sessionStorage.setItem(visitKey,'1');}welcome();}
  if(kiosk&&!preview){let idle;const reset=()=>{clearTimeout(idle);idle=setTimeout(resetKiosk,120000);};for(const ev of ['pointerdown','keydown','touchstart'])document.addEventListener(ev,reset,{passive:true});reset();}
  timers.push(setInterval(refreshResults,5000));
}
