import {h,field,selectField} from './ui.mjs';
export function question(q,onChange=()=>{}){const box=h('fieldset',{class:'question','data-code':q.code},h('legend',{},q.title,q.required?h('span',{class:'required'},' *'):null),q.body?h('p',{class:'muted'},q.body):null);let get=()=>null;
const id='q-'+crypto.randomUUID();
if(['single_choice','multiple_choice','image_choice','yes_no','quiz'].includes(q.qtype)){const choices=q.qtype==='yes_no'?[{key:'yes',label:'نعم'},{key:'no',label:'لا'}]:q.options;const nodes=choices.map(o=>{const input=h('input',{type:q.qtype==='multiple_choice'?'checkbox':'radio',name:id,value:o.key,onchange:onChange});box.append(h('label',{class:'choice'},input,o.media?h('img',{src:o.media,alt:o.label}):null,h('span',{},o.label)));return input;});if(q.qtype==='multiple_choice'&&(q.selection_min||q.selection_max))box.append(h('small',{class:'muted selection-hint'},[q.selection_min?`اختر ${q.selection_min} على الأقل`:null,q.selection_max?`حتى ${q.selection_max} خيارات`:null].filter(Boolean).join(' · ')));get=()=>q.qtype==='multiple_choice'?nodes.filter(x=>x.checked).map(x=>x.value):nodes.find(x=>x.checked)?.value??null;}
else if(q.qtype==='dropdown'){const f=selectField('اختر إجابة',[['','اختر…'],...q.options.map(o=>[o.key,o.label])],'');f.input.addEventListener('change',onChange);box.append(f.node);get=()=>f.input.value||null;}
else if(['rating','nps','emoji'].includes(q.qtype)){let val=null;const labels=h('div',{class:'scale-labels'},h('span',{},q.min_label||''),h('span',{},q.max_label||''));const options=h('div',{class:'scale'});for(let i=q.min;i<=q.max;i++){const emojis=['😞','🙁','😐','🙂','🤩'];const b=h('button',{type:'button',class:'scale-choice','aria-label':String(i),onclick:()=>{val=i;for(const x of options.children)x.classList.remove('selected');b.classList.add('selected');onChange();}},q.qtype==='emoji'?emojis[Math.min(4,Math.max(0,i-1))]+' '+i:q.qtype==='rating'&&q.max===5?'★ '+i:String(i));options.append(b);}box.append(options,labels);get=()=>val;}
else if(q.qtype==='slider'){const input=h('input',{type:'range',min:q.min,max:q.max,step:1,value:q.min}),output=h('output',{},'لم يتم الاختيار');let touched=false;input.addEventListener('input',()=>{touched=true;output.textContent=input.value;onChange();});box.append(h('div',{class:'scale-labels'},h('span',{},q.min_label||q.min),h('span',{},q.max_label||q.max)),input,output);get=()=>touched?Number(input.value):null;}
else if(q.qtype==='ranking'){const wrap=h('div',{class:'ranking'});const data=q.options.slice();let touched=false;function draw(){wrap.replaceChildren();data.forEach((o,i)=>wrap.append(h('div',{class:'rank-row'},h('span',{},i+1+'. '+o.label),h('button',{type:'button',disabled:i===0,onclick:()=>{[data[i-1],data[i]]=[data[i],data[i-1]];touched=true;draw();onChange();}},'↑'),h('button',{type:'button',disabled:i===data.length-1,onclick:()=>{[data[i+1],data[i]]=[data[i],data[i+1]];touched=true;draw();onChange();}},'↓'))));}draw();const accept=h('input',{type:'checkbox',onchange:()=>{touched=accept.checked;onChange();}});box.append(wrap,h('label',{class:'check'},accept,'اعتماد هذا الترتيب'));get=()=>touched?data.map(o=>o.key):null;}
else if(q.qtype==='allocation'){const inputs={};const wrap=h('div',{class:'allocation'});for(const o of q.options){const f=field(o.label,'number',0,{min:0,max:100,step:1,oninput:onChange});inputs[o.key]=f.input;wrap.append(f.node);}const total=h('strong',{},'المجموع: 0 / 100');wrap.addEventListener('input',()=>{const n=Object.values(inputs).reduce((a,x)=>a+Number(x.value||0),0);total.textContent='المجموع: '+n+' / 100';total.classList.toggle('warning',n!==100);});box.append(wrap,total);get=()=>Object.fromEntries(Object.entries(inputs).map(([k,x])=>[k,Number(x.value||0)]));}
else if(q.qtype==='matrix'){const inputs={};if(q.min_label||q.max_label)box.append(h('div',{class:'scale-labels'},h('span',{},q.min_label||q.min),h('span',{},q.max_label||q.max)));for(const row of q.rows){const opts=[['','اختر'],...Array.from({length:q.max-q.min+1},(_,i)=>[String(q.min+i),String(q.min+i)])];const f=selectField(row,opts,'');inputs[row]=f.input;f.input.addEventListener('change',onChange);box.append(f.node);}get=()=>Object.fromEntries(Object.entries(inputs).filter(([k,v])=>v.value!=='').map(([k,v])=>[k,Number(v.value)]));}
else if(q.qtype==='consent'){const input=h('input',{type:'checkbox',onchange:onChange});box.append(h('label',{class:'check consent-box'},input,q.body||'أوافق'));get=()=>input.checked?true:null;}
else {const mapped={number:'number',currency:'number',long_text:'textarea',date:'date',time:'time',datetime:'datetime-local',email:'email',phone:'tel',url:'url'};const type=mapped[q.qtype]||'text';const labels={date:'اختر التاريخ',time:'اختر الوقت',datetime:'اختر التاريخ والوقت',email:'البريد الإلكتروني',phone:'رقم الهاتف',url:'الرابط',number:'أدخل الرقم',currency:'أدخل المبلغ',long_text:'اكتب إجابتك',short_text:'اكتب إجابتك'};const f=field(labels[q.qtype]||'الإجابة',type,'',{maxlength:q.qtype==='long_text'?4000:500,placeholder:q.placeholder||'',min:['number','currency'].includes(q.qtype)?q.min:undefined,max:['number','currency'].includes(q.qtype)?q.max:undefined,step:['number','currency'].includes(q.qtype)?'any':q.qtype==='time'?'60':undefined,oninput:onChange});box.append(f.node);get=()=>f.input.value===''?null:['number','currency'].includes(q.qtype)?Number(f.input.value):f.input.value;}
return{node:box,get};}
export function visible(q,answers){if(!q.show_if)return true;const x=answers[q.show_if.code],v=q.show_if.equals;return Array.isArray(x)?x.includes(v):String(x).toLowerCase()===String(v).toLowerCase();}
