export function h(tag,attrs={},...children){const e=document.createElement(tag);for(const[k,v]of Object.entries(attrs||{})){if(v===undefined||v===null||v===false)continue;if(k==='class')e.className=v;else if(k==='text')e.textContent=v;else if(k==='checked')e.checked=!!v;else if(k==='value')e.value=v;else if(k.startsWith('on'))e.addEventListener(k.slice(2).toLowerCase(),v);else e.setAttribute(k,v===true?'':String(v));}for(const child of children.flat(Infinity)){if(child!==undefined&&child!==null&&child!==false)e.append(child instanceof Node?child:document.createTextNode(String(child)));}return e;}
export const $=s=>document.querySelector(s);
export const root=document.getElementById('app');
let csrf='';export function setCSRF(t){csrf=t||'';}
export async function api(path,body,method=body===undefined?'GET':'POST'){const ctl=new AbortController();const timer=setTimeout(()=>ctl.abort(),12000);try{const r=await fetch(path,{method,credentials:'same-origin',cache:'no-store',signal:ctl.signal,headers:{...(body!==undefined?{'Content-Type':'application/json'}:{}),...(csrf?{'X-CSRF':csrf}:{})},body:body===undefined?undefined:JSON.stringify(body)});let x;try{x=await r.json();}catch{x={detail:'SERVER_RESPONSE_INVALID'};}if(!r.ok){const e=new Error(typeof x.detail==='string'?x.detail:JSON.stringify(x.detail));e.status=r.status;throw e;}return x;}finally{clearTimeout(timer);}}
const messages={CODE_INVALID:'استخدم رمزًا ثابتًا من أحرف وأرقام إنجليزية فقط.',COLOR_INVALID:'اختر لونًا بصيغة صحيحة.',TEXT_LENGTH:'أكمل الحقول المطلوبة ضمن الطول المسموح.',DUPLICATE_CODE:'يوجد رمز مكرر. استخدم رمزًا مختلفًا لكل مادة.',QUESTION_TYPE_INVALID:'نوع السؤال غير مدعوم في هذه النسخة.',MATRIX_ROWS_REQUIRED:'أدخل صفوف المصفوفة دون تكرار.',OPTIONS_NOT_APPLICABLE:'هذا النوع لا يحتاج خيارات؛ أفرغ حقل الخيارات.',RANGE_INVALID:'يجب أن تكون أقل قيمة أصغر من أعلى قيمة.',TIMEZONE_REQUIRED:'استخدم تاريخًا يتضمن المنطقة الزمنية.',HTTPS_URL_REQUIRED:'أدخل رابط HTTPS أو مسار وسائط صحيحًا.',DATE_RANGE:'وقت النهاية يجب أن يكون بعد البداية.',ANSWER_REQUIRED:'أكمل السؤال المطلوب',NO_RECORDS:'الملف لا يحتوي سجلات قابلة للاستيراد.',SLUG_EXISTS:'هذا الرمز مستخدم في رابط آخر.',FORBIDDEN_ROLE:'هذه العملية غير متاحة لدورك.',LOGIN_REQUIRED:'يلزم تسجيل الدخول.',INVALID_CREDENTIALS:'بيانات الدخول غير صحيحة.',FORBIDDEN_SCOPE:'ليس لديك صلاحية لهذه الجهة.',POLL_CLOSED:'أُغلق التصويت. لم يُحتسب الطلب.',ALREADY_VOTED_OR_RECORDED:'سبق تسجيل التصويت لهذه الجلسة/الهوية المتصفحية.',OPTIONS_REQUIRED:'أضف خيارين على الأقل.',DRAFT_CHANGED_REFRESH_REQUIRED:'عُدلت المسودة في جلسة أخرى. أعد تحميلها قبل الحفظ.',DRAFT_CHANGED_REPREVIEW_REQUIRED:'تغيرت المسودة. أعد معاينة الاستيراد.',PASSWORD_12_TO_256_CHARACTERS:'كلمة المرور يجب ألا تقل عن 12 حرفًا.',CONTACT_CONSENT_REQUIRED:'يلزم قبول مشاركة بيانات التواصل.',TIME_INVALID:'أدخل وقتًا صحيحًا.',DATE_INVALID:'أدخل تاريخًا صحيحًا.',DATETIME_INVALID:'أدخل تاريخًا ووقتًا صحيحين.',SURVEY_NOT_DEFINED:'اختر استبيانًا موجودًا أولًا.',SURVEY_ID_INVALID:'رمز الاستبيان غير صحيح أو مكرر.',SURVEYS_INVALID:'بيانات الاستبيانات غير صحيحة.',EMAIL_INVALID:'أدخل بريدًا إلكترونيًا صحيحًا.',PHONE_INVALID:'أدخل رقم هاتف صحيحًا.'};
export function msg(e){return messages[e?.message||e]||e?.message||String(e);}
export function toast(t,error=false){const el=h('div',{class:'toast'+(error?' error':'')},t);$('#toasts').append(el);setTimeout(()=>el.remove(),7000);}
export function button(t,fn,cls='btn'){return h('button',{type:'button',class:cls,onclick:async ev=>{const b=ev.currentTarget;try{b.disabled=true;await fn(ev);}catch(e){toast(msg(e),true);}finally{b.disabled=false;}}},t);}
export function field(label,type='text',value='',attrs={}){const input=h(type==='textarea'?'textarea':'input',{type:type==='textarea'?undefined:type,value: value??'','aria-label':label,...attrs});const node=h('label',{class:'field'},h('span',{},label),input);return {node,input};}
export function selectField(label,options,value){const el=h('select',{'aria-label':label});for(const o of options){const pair=Array.isArray(o)?o:[o,o];el.append(h('option',{value:pair[0]},pair[1]));}el.value=value??'';return{node:h('label',{class:'field'},h('span',{},label),el),input:el};}
export function check(label,value=false){const el=h('input',{type:'checkbox',checked:value});return{node:h('label',{class:'check'},el,label),input:el};}
export function modal(title,body,wide=false){const d=h('dialog',{class:wide?'modal wide':'modal'},h('header',{},h('h2',{},title),button('×',()=>d.close(),'icon-btn')),body);document.body.append(d);d.addEventListener('close',()=>d.remove());d.showModal();return d;}
export function download(name,data,type='application/json'){const a=h('a',{href:URL.createObjectURL(new Blob([data],{type})),download:name});a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
export const labels={participant:'المشاركون',sponsor:'الرعاة',session:'البرنامج والأحداث',place:'الأماكن والمخططات',fact:'الحقائق والإحصائيات',service:'الخدمات',question:'الأسئلة والاستبيانات',poll:'التصويت',offer:'العروض',ad:'الإعلانات',media:'مكتبة العرض',contact:'التواصل',news:'المستجدات'};
export const types={single_choice:'اختيار واحد',multiple_choice:'اختيارات متعددة',image_choice:'اختيار بالصور',yes_no:'نعم / لا',short_text:'نص قصير',long_text:'نص طويل',number:'رقم',rating:'تقييم رقمي',nps:'مؤشر التوصية NPS',slider:'شريط تدريجي',ranking:'ترتيب الخيارات',matrix:'مصفوفة تقييم',emoji:'تقييم تعبيري',date:'تاريخ',time:'وقت',datetime:'تاريخ ووقت',email:'بريد إلكتروني',phone:'رقم هاتف',url:'رابط',consent:'موافقة',allocation:'توزيع 100 نقطة',quiz:'اختبار / إجابة صحيحة'};
export function media(r,cls='record-media'){if(!r.media)return null;return r.media_type==='video'?h('video',{class:cls,src:r.media,controls:true,muted:true,preload:'metadata',playsinline:true}):h('img',{class:cls,src:r.media,alt:r.title||'',loading:'lazy',onerror:e=>{e.currentTarget.hidden=true;}});}
export function brand(title='PulseX',mark='P',href='/'){return h('a',{href,class:'brand'},h('span',{class:'brandmark'},mark||'P'),h('span',{},title));}

export function isoToLocalInput(v){if(!v)return'';const d=new Date(v);if(Number.isNaN(d.getTime()))return String(v).slice(0,16);const z=n=>String(n).padStart(2,'0');return `${d.getFullYear()}-${z(d.getMonth()+1)}-${z(d.getDate())}T${z(d.getHours())}:${z(d.getMinutes())}`;}
export function localInputToISO(v){if(!v)return'';const d=new Date(v);if(Number.isNaN(d.getTime()))throw new Error('DATETIME_INVALID');return d.toISOString();}
